=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.05
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'cgi'

module VPNDetection
  class LookupApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Lookup
    # Answers what is known about a single IPv4 or IPv6 address. Which fields come back is decided by the plan behind the presented key; with no key the answer is `ip` and `is_vpn`. 
    # @param ip [String] The IPv4 or IPv6 address to classify.
    # @param [Hash] opts the optional parameters
    # @return [LookupResponse]
    def lookup_ip(ip, opts = {})
      data, _status_code, _headers = lookup_ip_with_http_info(ip, opts)
      data
    end

    # Lookup
    # Answers what is known about a single IPv4 or IPv6 address. Which fields come back is decided by the plan behind the presented key; with no key the answer is &#x60;ip&#x60; and &#x60;is_vpn&#x60;. 
    # @param ip [String] The IPv4 or IPv6 address to classify.
    # @param [Hash] opts the optional parameters
    # @return [Array<(LookupResponse, Integer, Hash)>] LookupResponse data, response status code and response headers
    def lookup_ip_with_http_info(ip, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LookupApi.lookup_ip ...'
      end
      # verify the required parameter 'ip' is set
      if @api_client.config.client_side_validation && ip.nil?
        fail ArgumentError, "Missing the required parameter 'ip' when calling LookupApi.lookup_ip"
      end
      # resource path
      local_var_path = '/{ip}'.sub('{ip}', CGI.escape(ip.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'LookupResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyQuery', 'bearerAuth', 'apiKeyHeader']

      new_options = opts.merge(
        :operation => :"LookupApi.lookup_ip",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LookupApi#lookup_ip\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
