=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.16
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  class AccountCreatedApikey < ApiModelBase
    attr_accessor :rc

    attr_accessor :id

    attr_accessor :name

    # The secret. Returned once, here, and never again.
    attr_accessor :key

    attr_accessor :key_prefix

    attr_accessor :allowed_cidrs

    attr_accessor :allowed_scopes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rc' => :'rc',
        :'id' => :'id',
        :'name' => :'name',
        :'key' => :'key',
        :'key_prefix' => :'key_prefix',
        :'allowed_cidrs' => :'allowed_cidrs',
        :'allowed_scopes' => :'allowed_scopes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rc' => :'String',
        :'id' => :'String',
        :'name' => :'String',
        :'key' => :'String',
        :'key_prefix' => :'String',
        :'allowed_cidrs' => :'Array<String>',
        :'allowed_scopes' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VPNDetection::AccountCreatedApikey` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VPNDetection::AccountCreatedApikey`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rc')
        self.rc = attributes[:'rc']
      else
        self.rc = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'key')
        self.key = attributes[:'key']
      else
        self.key = nil
      end

      if attributes.key?(:'key_prefix')
        self.key_prefix = attributes[:'key_prefix']
      end

      if attributes.key?(:'allowed_cidrs')
        if (value = attributes[:'allowed_cidrs']).is_a?(Array)
          self.allowed_cidrs = value
        end
      end

      if attributes.key?(:'allowed_scopes')
        if (value = attributes[:'allowed_scopes']).is_a?(Array)
          self.allowed_scopes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @rc.nil?
        invalid_properties.push('invalid value for "rc", rc cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @key.nil?
        invalid_properties.push('invalid value for "key", key cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @rc.nil?
      return false if @id.nil?
      return false if @key.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] rc Value to be assigned
    def rc=(rc)
      if rc.nil?
        fail ArgumentError, 'rc cannot be nil'
      end

      @rc = rc
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] key Value to be assigned
    def key=(key)
      if key.nil?
        fail ArgumentError, 'key cannot be nil'
      end

      @key = key
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rc == o.rc &&
          id == o.id &&
          name == o.name &&
          key == o.key &&
          key_prefix == o.key_prefix &&
          allowed_cidrs == o.allowed_cidrs &&
          allowed_scopes == o.allowed_scopes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rc, id, name, key, key_prefix, allowed_cidrs, allowed_scopes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
