=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.18
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  # The published digests for one database file.
  class DbChecksums < ApiModelBase
    attr_accessor :md5

    attr_accessor :sha1

    attr_accessor :sha256

    attr_accessor :sha512

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'md5' => :'md5',
        :'sha1' => :'sha1',
        :'sha256' => :'sha256',
        :'sha512' => :'sha512'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'md5' => :'String',
        :'sha1' => :'String',
        :'sha256' => :'String',
        :'sha512' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VPNDetection::DbChecksums` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VPNDetection::DbChecksums`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'md5')
        self.md5 = attributes[:'md5']
      else
        self.md5 = nil
      end

      if attributes.key?(:'sha1')
        self.sha1 = attributes[:'sha1']
      else
        self.sha1 = nil
      end

      if attributes.key?(:'sha256')
        self.sha256 = attributes[:'sha256']
      else
        self.sha256 = nil
      end

      if attributes.key?(:'sha512')
        self.sha512 = attributes[:'sha512']
      else
        self.sha512 = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @md5.nil?
        invalid_properties.push('invalid value for "md5", md5 cannot be nil.')
      end

      if @sha1.nil?
        invalid_properties.push('invalid value for "sha1", sha1 cannot be nil.')
      end

      if @sha256.nil?
        invalid_properties.push('invalid value for "sha256", sha256 cannot be nil.')
      end

      if @sha512.nil?
        invalid_properties.push('invalid value for "sha512", sha512 cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @md5.nil?
      return false if @sha1.nil?
      return false if @sha256.nil?
      return false if @sha512.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] md5 Value to be assigned
    def md5=(md5)
      if md5.nil?
        fail ArgumentError, 'md5 cannot be nil'
      end

      @md5 = md5
    end

    # Custom attribute writer method with validation
    # @param [Object] sha1 Value to be assigned
    def sha1=(sha1)
      if sha1.nil?
        fail ArgumentError, 'sha1 cannot be nil'
      end

      @sha1 = sha1
    end

    # Custom attribute writer method with validation
    # @param [Object] sha256 Value to be assigned
    def sha256=(sha256)
      if sha256.nil?
        fail ArgumentError, 'sha256 cannot be nil'
      end

      @sha256 = sha256
    end

    # Custom attribute writer method with validation
    # @param [Object] sha512 Value to be assigned
    def sha512=(sha512)
      if sha512.nil?
        fail ArgumentError, 'sha512 cannot be nil'
      end

      @sha512 = sha512
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          md5 == o.md5 &&
          sha1 == o.sha1 &&
          sha256 == o.sha256 &&
          sha512 == o.sha512
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [md5, sha1, sha256, sha512].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
