=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.15
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  class DeviceAuthorization < ApiModelBase
    # Yours. Poll with it; never show it to anyone.
    attr_accessor :device_code

    # Short and typable. This is what the person confirms.
    attr_accessor :user_code

    attr_accessor :verification_uri

    # The same page with the code already filled in.
    attr_accessor :verification_uri_complete

    attr_accessor :expires_in

    # Seconds between polls.
    attr_accessor :interval

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'device_code' => :'device_code',
        :'user_code' => :'user_code',
        :'verification_uri' => :'verification_uri',
        :'verification_uri_complete' => :'verification_uri_complete',
        :'expires_in' => :'expires_in',
        :'interval' => :'interval'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'device_code' => :'String',
        :'user_code' => :'String',
        :'verification_uri' => :'String',
        :'verification_uri_complete' => :'String',
        :'expires_in' => :'Integer',
        :'interval' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VPNDetection::DeviceAuthorization` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VPNDetection::DeviceAuthorization`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'device_code')
        self.device_code = attributes[:'device_code']
      else
        self.device_code = nil
      end

      if attributes.key?(:'user_code')
        self.user_code = attributes[:'user_code']
      else
        self.user_code = nil
      end

      if attributes.key?(:'verification_uri')
        self.verification_uri = attributes[:'verification_uri']
      else
        self.verification_uri = nil
      end

      if attributes.key?(:'verification_uri_complete')
        self.verification_uri_complete = attributes[:'verification_uri_complete']
      end

      if attributes.key?(:'expires_in')
        self.expires_in = attributes[:'expires_in']
      else
        self.expires_in = nil
      end

      if attributes.key?(:'interval')
        self.interval = attributes[:'interval']
      else
        self.interval = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @device_code.nil?
        invalid_properties.push('invalid value for "device_code", device_code cannot be nil.')
      end

      if @user_code.nil?
        invalid_properties.push('invalid value for "user_code", user_code cannot be nil.')
      end

      if @verification_uri.nil?
        invalid_properties.push('invalid value for "verification_uri", verification_uri cannot be nil.')
      end

      if @expires_in.nil?
        invalid_properties.push('invalid value for "expires_in", expires_in cannot be nil.')
      end

      if @interval.nil?
        invalid_properties.push('invalid value for "interval", interval cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @device_code.nil?
      return false if @user_code.nil?
      return false if @verification_uri.nil?
      return false if @expires_in.nil?
      return false if @interval.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] device_code Value to be assigned
    def device_code=(device_code)
      if device_code.nil?
        fail ArgumentError, 'device_code cannot be nil'
      end

      @device_code = device_code
    end

    # Custom attribute writer method with validation
    # @param [Object] user_code Value to be assigned
    def user_code=(user_code)
      if user_code.nil?
        fail ArgumentError, 'user_code cannot be nil'
      end

      @user_code = user_code
    end

    # Custom attribute writer method with validation
    # @param [Object] verification_uri Value to be assigned
    def verification_uri=(verification_uri)
      if verification_uri.nil?
        fail ArgumentError, 'verification_uri cannot be nil'
      end

      @verification_uri = verification_uri
    end

    # Custom attribute writer method with validation
    # @param [Object] expires_in Value to be assigned
    def expires_in=(expires_in)
      if expires_in.nil?
        fail ArgumentError, 'expires_in cannot be nil'
      end

      @expires_in = expires_in
    end

    # Custom attribute writer method with validation
    # @param [Object] interval Value to be assigned
    def interval=(interval)
      if interval.nil?
        fail ArgumentError, 'interval cannot be nil'
      end

      @interval = interval
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          device_code == o.device_code &&
          user_code == o.user_code &&
          verification_uri == o.verification_uri &&
          verification_uri_complete == o.verification_uri_complete &&
          expires_in == o.expires_in &&
          interval == o.interval
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [device_code, user_code, verification_uri, verification_uri_complete, expires_in, interval].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
