=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.16
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  class EntitlementUsage < ApiModelBase
    # Requests counted in the current window. The same number the lookup API gates on, and it can lag by a few seconds. 
    attr_accessor :requests

    # What the plan includes. Zero on a plan that includes none.
    attr_accessor :quota

    # Where we stop serving. NULL means never, which is the normal state of an uncapped paid plan and is not the same as zero. Above the quota and below this, requests are served and billed as overage. 
    attr_accessor :hard_limit

    # When the current allowance period began.
    attr_accessor :window_start

    # When the allowance next resets.
    attr_accessor :window_end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'requests' => :'requests',
        :'quota' => :'quota',
        :'hard_limit' => :'hard_limit',
        :'window_start' => :'window_start',
        :'window_end' => :'window_end'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'requests' => :'Integer',
        :'quota' => :'Integer',
        :'hard_limit' => :'Integer',
        :'window_start' => :'Time',
        :'window_end' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'hard_limit',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VPNDetection::EntitlementUsage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VPNDetection::EntitlementUsage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'requests')
        self.requests = attributes[:'requests']
      else
        self.requests = nil
      end

      if attributes.key?(:'quota')
        self.quota = attributes[:'quota']
      else
        self.quota = nil
      end

      if attributes.key?(:'hard_limit')
        self.hard_limit = attributes[:'hard_limit']
      else
        self.hard_limit = nil
      end

      if attributes.key?(:'window_start')
        self.window_start = attributes[:'window_start']
      else
        self.window_start = nil
      end

      if attributes.key?(:'window_end')
        self.window_end = attributes[:'window_end']
      else
        self.window_end = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @requests.nil?
        invalid_properties.push('invalid value for "requests", requests cannot be nil.')
      end

      if @quota.nil?
        invalid_properties.push('invalid value for "quota", quota cannot be nil.')
      end

      if @window_start.nil?
        invalid_properties.push('invalid value for "window_start", window_start cannot be nil.')
      end

      if @window_end.nil?
        invalid_properties.push('invalid value for "window_end", window_end cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @requests.nil?
      return false if @quota.nil?
      return false if @window_start.nil?
      return false if @window_end.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] requests Value to be assigned
    def requests=(requests)
      if requests.nil?
        fail ArgumentError, 'requests cannot be nil'
      end

      @requests = requests
    end

    # Custom attribute writer method with validation
    # @param [Object] quota Value to be assigned
    def quota=(quota)
      if quota.nil?
        fail ArgumentError, 'quota cannot be nil'
      end

      @quota = quota
    end

    # Custom attribute writer method with validation
    # @param [Object] window_start Value to be assigned
    def window_start=(window_start)
      if window_start.nil?
        fail ArgumentError, 'window_start cannot be nil'
      end

      @window_start = window_start
    end

    # Custom attribute writer method with validation
    # @param [Object] window_end Value to be assigned
    def window_end=(window_end)
      if window_end.nil?
        fail ArgumentError, 'window_end cannot be nil'
      end

      @window_end = window_end
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          requests == o.requests &&
          quota == o.quota &&
          hard_limit == o.hard_limit &&
          window_start == o.window_start &&
          window_end == o.window_end
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [requests, quota, hard_limit, window_start, window_end].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
