=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.04
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  # The union of every plan's answer. Only `ip` and `is_vpn` are guaranteed; each remaining field is present when your plan includes it, and absent otherwise. A client that must work across plans should treat an absent flag as unknown rather than as `false`. 
  class LookupResponse < ApiModelBase
    # The address that was looked up, normalized.
    attr_accessor :ip

    # Whether the address is VPN infrastructure. Keys off presence in the VPN dataset, so an unattributed range with no provider is still `true`. 
    attr_accessor :is_vpn

    # Whether the address belongs to a hosting or cloud provider. Starter and above.
    attr_accessor :is_hosting

    # Whether the address is a privacy relay egress. Starter and above.
    attr_accessor :is_relay

    # Whether the address is a Tor node. Starter and above.
    attr_accessor :is_tor

    # Whether the address belongs to a CDN. Starter and above.
    attr_accessor :is_cdn

    # Whether the address was seen in a residential proxy pool. Max only.
    attr_accessor :is_resproxy

    # Whether the address was seen in a datacenter proxy pool. Max only.
    attr_accessor :is_dcproxy

    # Whether the address was seen in a mobile proxy pool. Max only.
    attr_accessor :is_mobproxy

    # Detail for `is_vpn`. Empty when `is_vpn` is false. Starter and above. 
    attr_accessor :vpn

    # Detail for `is_hosting`. Empty when false. Scale and above.
    attr_accessor :hosting

    # Detail for `is_relay`. Empty when false. Scale and above.
    attr_accessor :relay

    # Detail for `is_tor`. Empty when false. Scale and above. The tor dataset carries no provider, so `provider` is always an empty string. 
    attr_accessor :tor

    # Detail for `is_cdn`. Empty when false. Scale and above.
    attr_accessor :cdn

    # Detail for `is_resproxy`. Empty when false. Max only.
    attr_accessor :resproxy

    # Detail for `is_dcproxy`. Empty when false. Max only.
    attr_accessor :dcproxy

    # Detail for `is_mobproxy`. Empty when false. Max only.
    attr_accessor :mobproxy

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ip' => :'ip',
        :'is_vpn' => :'is_vpn',
        :'is_hosting' => :'is_hosting',
        :'is_relay' => :'is_relay',
        :'is_tor' => :'is_tor',
        :'is_cdn' => :'is_cdn',
        :'is_resproxy' => :'is_resproxy',
        :'is_dcproxy' => :'is_dcproxy',
        :'is_mobproxy' => :'is_mobproxy',
        :'vpn' => :'vpn',
        :'hosting' => :'hosting',
        :'relay' => :'relay',
        :'tor' => :'tor',
        :'cdn' => :'cdn',
        :'resproxy' => :'resproxy',
        :'dcproxy' => :'dcproxy',
        :'mobproxy' => :'mobproxy'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ip' => :'String',
        :'is_vpn' => :'Boolean',
        :'is_hosting' => :'Boolean',
        :'is_relay' => :'Boolean',
        :'is_tor' => :'Boolean',
        :'is_cdn' => :'Boolean',
        :'is_resproxy' => :'Boolean',
        :'is_dcproxy' => :'Boolean',
        :'is_mobproxy' => :'Boolean',
        :'vpn' => :'VpnDetail',
        :'hosting' => :'ClassDetail',
        :'relay' => :'ClassDetail',
        :'tor' => :'ClassDetail',
        :'cdn' => :'ClassDetail',
        :'resproxy' => :'ProxyDetail',
        :'dcproxy' => :'ProxyDetail',
        :'mobproxy' => :'ProxyDetail'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VPNDetection::LookupResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VPNDetection::LookupResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ip')
        self.ip = attributes[:'ip']
      else
        self.ip = nil
      end

      if attributes.key?(:'is_vpn')
        self.is_vpn = attributes[:'is_vpn']
      else
        self.is_vpn = nil
      end

      if attributes.key?(:'is_hosting')
        self.is_hosting = attributes[:'is_hosting']
      end

      if attributes.key?(:'is_relay')
        self.is_relay = attributes[:'is_relay']
      end

      if attributes.key?(:'is_tor')
        self.is_tor = attributes[:'is_tor']
      end

      if attributes.key?(:'is_cdn')
        self.is_cdn = attributes[:'is_cdn']
      end

      if attributes.key?(:'is_resproxy')
        self.is_resproxy = attributes[:'is_resproxy']
      end

      if attributes.key?(:'is_dcproxy')
        self.is_dcproxy = attributes[:'is_dcproxy']
      end

      if attributes.key?(:'is_mobproxy')
        self.is_mobproxy = attributes[:'is_mobproxy']
      end

      if attributes.key?(:'vpn')
        self.vpn = attributes[:'vpn']
      end

      if attributes.key?(:'hosting')
        self.hosting = attributes[:'hosting']
      end

      if attributes.key?(:'relay')
        self.relay = attributes[:'relay']
      end

      if attributes.key?(:'tor')
        self.tor = attributes[:'tor']
      end

      if attributes.key?(:'cdn')
        self.cdn = attributes[:'cdn']
      end

      if attributes.key?(:'resproxy')
        self.resproxy = attributes[:'resproxy']
      end

      if attributes.key?(:'dcproxy')
        self.dcproxy = attributes[:'dcproxy']
      end

      if attributes.key?(:'mobproxy')
        self.mobproxy = attributes[:'mobproxy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @ip.nil?
        invalid_properties.push('invalid value for "ip", ip cannot be nil.')
      end

      if @is_vpn.nil?
        invalid_properties.push('invalid value for "is_vpn", is_vpn cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @ip.nil?
      return false if @is_vpn.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ip Value to be assigned
    def ip=(ip)
      if ip.nil?
        fail ArgumentError, 'ip cannot be nil'
      end

      @ip = ip
    end

    # Custom attribute writer method with validation
    # @param [Object] is_vpn Value to be assigned
    def is_vpn=(is_vpn)
      if is_vpn.nil?
        fail ArgumentError, 'is_vpn cannot be nil'
      end

      @is_vpn = is_vpn
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ip == o.ip &&
          is_vpn == o.is_vpn &&
          is_hosting == o.is_hosting &&
          is_relay == o.is_relay &&
          is_tor == o.is_tor &&
          is_cdn == o.is_cdn &&
          is_resproxy == o.is_resproxy &&
          is_dcproxy == o.is_dcproxy &&
          is_mobproxy == o.is_mobproxy &&
          vpn == o.vpn &&
          hosting == o.hosting &&
          relay == o.relay &&
          tor == o.tor &&
          cdn == o.cdn &&
          resproxy == o.resproxy &&
          dcproxy == o.dcproxy &&
          mobproxy == o.mobproxy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ip, is_vpn, is_hosting, is_relay, is_tor, is_cdn, is_resproxy, is_dcproxy, is_mobproxy, vpn, hosting, relay, tor, cdn, resproxy, dcproxy, mobproxy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
