=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.15
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  class OauthMetadata < ApiModelBase
    attr_accessor :issuer

    attr_accessor :authorization_endpoint

    attr_accessor :token_endpoint

    attr_accessor :device_authorization_endpoint

    attr_accessor :revocation_endpoint

    attr_accessor :scopes_supported

    attr_accessor :response_types_supported

    attr_accessor :grant_types_supported

    attr_accessor :code_challenge_methods_supported

    # A client_id may be an https URL serving your client metadata.
    attr_accessor :client_id_metadata_document_supported

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'issuer' => :'issuer',
        :'authorization_endpoint' => :'authorization_endpoint',
        :'token_endpoint' => :'token_endpoint',
        :'device_authorization_endpoint' => :'device_authorization_endpoint',
        :'revocation_endpoint' => :'revocation_endpoint',
        :'scopes_supported' => :'scopes_supported',
        :'response_types_supported' => :'response_types_supported',
        :'grant_types_supported' => :'grant_types_supported',
        :'code_challenge_methods_supported' => :'code_challenge_methods_supported',
        :'client_id_metadata_document_supported' => :'client_id_metadata_document_supported'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'issuer' => :'String',
        :'authorization_endpoint' => :'String',
        :'token_endpoint' => :'String',
        :'device_authorization_endpoint' => :'String',
        :'revocation_endpoint' => :'String',
        :'scopes_supported' => :'Array<String>',
        :'response_types_supported' => :'Array<String>',
        :'grant_types_supported' => :'Array<String>',
        :'code_challenge_methods_supported' => :'Array<String>',
        :'client_id_metadata_document_supported' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VPNDetection::OauthMetadata` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VPNDetection::OauthMetadata`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'issuer')
        self.issuer = attributes[:'issuer']
      else
        self.issuer = nil
      end

      if attributes.key?(:'authorization_endpoint')
        self.authorization_endpoint = attributes[:'authorization_endpoint']
      else
        self.authorization_endpoint = nil
      end

      if attributes.key?(:'token_endpoint')
        self.token_endpoint = attributes[:'token_endpoint']
      else
        self.token_endpoint = nil
      end

      if attributes.key?(:'device_authorization_endpoint')
        self.device_authorization_endpoint = attributes[:'device_authorization_endpoint']
      end

      if attributes.key?(:'revocation_endpoint')
        self.revocation_endpoint = attributes[:'revocation_endpoint']
      end

      if attributes.key?(:'scopes_supported')
        if (value = attributes[:'scopes_supported']).is_a?(Array)
          self.scopes_supported = value
        end
      end

      if attributes.key?(:'response_types_supported')
        if (value = attributes[:'response_types_supported']).is_a?(Array)
          self.response_types_supported = value
        end
      end

      if attributes.key?(:'grant_types_supported')
        if (value = attributes[:'grant_types_supported']).is_a?(Array)
          self.grant_types_supported = value
        end
      end

      if attributes.key?(:'code_challenge_methods_supported')
        if (value = attributes[:'code_challenge_methods_supported']).is_a?(Array)
          self.code_challenge_methods_supported = value
        end
      end

      if attributes.key?(:'client_id_metadata_document_supported')
        self.client_id_metadata_document_supported = attributes[:'client_id_metadata_document_supported']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @issuer.nil?
        invalid_properties.push('invalid value for "issuer", issuer cannot be nil.')
      end

      if @authorization_endpoint.nil?
        invalid_properties.push('invalid value for "authorization_endpoint", authorization_endpoint cannot be nil.')
      end

      if @token_endpoint.nil?
        invalid_properties.push('invalid value for "token_endpoint", token_endpoint cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @issuer.nil?
      return false if @authorization_endpoint.nil?
      return false if @token_endpoint.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] issuer Value to be assigned
    def issuer=(issuer)
      if issuer.nil?
        fail ArgumentError, 'issuer cannot be nil'
      end

      @issuer = issuer
    end

    # Custom attribute writer method with validation
    # @param [Object] authorization_endpoint Value to be assigned
    def authorization_endpoint=(authorization_endpoint)
      if authorization_endpoint.nil?
        fail ArgumentError, 'authorization_endpoint cannot be nil'
      end

      @authorization_endpoint = authorization_endpoint
    end

    # Custom attribute writer method with validation
    # @param [Object] token_endpoint Value to be assigned
    def token_endpoint=(token_endpoint)
      if token_endpoint.nil?
        fail ArgumentError, 'token_endpoint cannot be nil'
      end

      @token_endpoint = token_endpoint
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          issuer == o.issuer &&
          authorization_endpoint == o.authorization_endpoint &&
          token_endpoint == o.token_endpoint &&
          device_authorization_endpoint == o.device_authorization_endpoint &&
          revocation_endpoint == o.revocation_endpoint &&
          scopes_supported == o.scopes_supported &&
          response_types_supported == o.response_types_supported &&
          grant_types_supported == o.grant_types_supported &&
          code_challenge_methods_supported == o.code_challenge_methods_supported &&
          client_id_metadata_document_supported == o.client_id_metadata_document_supported
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [issuer, authorization_endpoint, token_endpoint, device_authorization_endpoint, revocation_endpoint, scopes_supported, response_types_supported, grant_types_supported, code_challenge_methods_supported, client_id_metadata_document_supported].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
