=begin
#VPNDetection API

#The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 

The version of the OpenAPI document: 2026.09.21
Contact: support@vpndetection.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module VPNDetection
  class Standing
    EXPIRED = "expired".freeze
    LICENSED = "licensed".freeze
    UNLICENSED = "unlicensed".freeze

    def self.all_vars
      @all_vars ||= [EXPIRED, LICENSED, UNLICENSED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Standing.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Standing"
    end
  end
end
